name: sipandu
description: Aplikasi pelaporan masyarakat

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.13
  geolocator: ^8.0.1
  geocoding: ^2.0.4
  http: ^0.13.6
  pocketbase: ^0.9.1
  dio: ^5.0.0
  image_picker_web: ^4.0.0
  mime: ^1.0.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true