// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkAm-6OZBPtRnNfc-SfMHtRYmItUcZ1jo',
    appId: '1:741436438006:web:3b15655bf43dc4b4be83d7',
    messagingSenderId: '741436438006',
    projectId: 'sipandu-ea21b',
    authDomain: 'sipandu-ea21b.firebaseapp.com',
    storageBucket: 'sipandu-ea21b.firebasestorage.app',
    measurementId: 'G-FZHD4K4PZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTOVnp4hNQmXdMq0iFYY2PKVXfgkWaDAk',
    appId: '1:741436438006:android:2e6e6f60104fc02abe83d7',
    messagingSenderId: '741436438006',
    projectId: 'sipandu-ea21b',
    storageBucket: 'sipandu-ea21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCccH6vjPsf7bf_WieKeRKv-0nmncamiKU',
    appId: '1:741436438006:ios:47bf61750a1caaf6be83d7',
    messagingSenderId: '741436438006',
    projectId: 'sipandu-ea21b',
    storageBucket: 'sipandu-ea21b.firebasestorage.app',
    iosBundleId: 'com.example.sipandu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCccH6vjPsf7bf_WieKeRKv-0nmncamiKU',
    appId: '1:741436438006:ios:47bf61750a1caaf6be83d7',
    messagingSenderId: '741436438006',
    projectId: 'sipandu-ea21b',
    storageBucket: 'sipandu-ea21b.firebasestorage.app',
    iosBundleId: 'com.example.sipandu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkAm-6OZBPtRnNfc-SfMHtRYmItUcZ1jo',
    appId: '1:741436438006:web:6cd67589f1aa234ebe83d7',
    messagingSenderId: '741436438006',
    projectId: 'sipandu-ea21b',
    authDomain: 'sipandu-ea21b.firebaseapp.com',
    storageBucket: 'sipandu-ea21b.firebasestorage.app',
    measurementId: 'G-MCEV3CKDMQ',
  );
}
